### ISSUE TITLE
[Bug]: Latest Fabric version is tagged as Forge on CF

### ISSUE THREAD

**Issue by LeFauxMatt** [someaddons/betterfpsdistances#10]
### Describe the bug you're experiencing

Better Fps - Render Distance[Fabric] 1.8 has the Forge tag which causes it to be unseen by Mod Loaders.

### Reproducability

![image](https://user-images.githubusercontent.com/3005344/169547418-0b9ac294-6d0d-476f-bdf1-111bdcab8c42.png)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Fabric

### Logs

na

**Comment by someaddons** [comment]
ops, fixed :D
