### ISSUE TITLE
Mod Description

### ISSUE THREAD

**Issue by Julienraptor01** [someaddons/betterfpsdistances#11]
The mod description is incorrect due to a change on how vanilla minecraft works. 
At starting with snapshot 21w37a chunk render in a cylinder shape.
https://minecraft.fandom.com/wiki/Java_Edition_21w37a
> Render distance now causes chunks to load in a cylinder shape around the player instead of a square.

**Comment by ghost** [comment]
The mod still renders chunks in a circle, but the fog is rendered in a cyllinder.

**Comment by someaddons** [comment]
ye I know, just didnt want an explanation for each minecraft version on the page. Added a small note
