### ISSUE TITLE
Some chunks not loading after roaming aroung the world for a bit

### ISSUE THREAD

**Issue by Sakatsuky** [someaddons/betterfpsdistances#14]
It happens only with this mod installed, when i remove it the chunks load without problem.
For testing i created some worlds and wandered for some seconds flying before some chunks stopping to load, On game settings i'm using 10 chunks.
It might be a bug with optfine UH7? Forge is 40.1.19.

the mods i'm using that i think might be the problem:
betterfpsdist-1.18.2-1.5
smoothchunk-1.18.2-1.9
dynview-1.18.2-2.8
betterbiomeblend-1.18.2-1.3.5-forge
TerraBlender-forge-1.18.2-1.1.0.101
BiomesOPlenty-1.18.2-16.0.0.115
OptiFine_1.18.2_HD_U_H7
Xaeros_Minimap_22.8.2_Forge_1.18.2
XaerosWorldMap_1.22.0_Forge_1.18.2

**Comment by someaddons** [comment]
Probably an optifine bug, this mod just changes the distance at which chunks no longer get renderered
