### ISSUE TITLE
License

### ISSUE THREAD

**Issue by srnyx** [someaddons/betterfpsdistances#16]
Could you change the license on CurseForge to allow it to be used in modpacks?
And could you also upload the license to GitHub?

**Comment by someaddons** [comment]
license is just ARR, you're allowed to include it in curseforge modpacks, that permission is actually granted when you upload a mod

**Comment by aaronliu0130** [comment]
Hi, do you allow the binary to be redistributed in a Modrinth modpack as an override mod as well?

**Comment by srnyx** [comment]
> Hi, do you allow the binary to be redistributed in a Modrinth modpack as an override mod as well?

No: https://github.com/someaddons/betterfpsdistances/issues/12#issuecomment-1149027128

**Comment by aaronliu0130** [comment]
Oh. Seems like a very weird choice.
