### ISSUE TITLE
[Bug]: Cannot see ground under you from high up.

### ISSUE THREAD

**Issue by Reshy** [someaddons/betterfpsdistances#18]
### Describe the bug you're experiencing

Due to the circular render distance, it's entirely possible not to be able to see the ground under you when up high which can be a bit disconcerting.

It might be worth having an option to set a minim cylinder render distance, just so you can see the ground if you're up high enough.

### Reproducability

Have a structure high in the sky, the ground will not be visible.

![2022-09-23_17 52 49](https://user-images.githubusercontent.com/2096384/192075859-26657bb7-77d1-4ca8-9b2b-126dba0610e9.png)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

None

**Comment by chief-turkler** [comment]
![2022-11-12_01 52 12](https://user-images.githubusercontent.com/49252967/201442440-2af9d0f4-0b49-4804-8cb1-42a6df016fea.png)

![2022-11-12_01 38 27](https://user-images.githubusercontent.com/49252967/201442455-8bca4fc6-399c-43a2-bc05-cea38b06edd2.png)

I can confirm this being the case, it also works in reverse as well. If you turn off nether fog then you can't even see the nether roof from a low point as the mod seems to stop rendering those points. I'm fairly certain an exception per dimension, along with a system that stretches the rendering bubble vertically as the player gets higher would solve this with very little edge cases.

**Comment by offbeat-stuff** [comment]
thats what the mod does, this the better fps feature

**Comment by someaddons** [comment]
ye thats kinda the point of the mod
