### ISSUE TITLE
[Question] Do you allow someone else to port it to other mc versions?

### ISSUE THREAD

**Issue by HowardZHY** [someaddons/betterfpsdistances#20]
### Describe the bug you're experiencing

like older fabric

### Reproducability

/

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16

### Modloader version

Fabric

### Logs

/

**Comment by HowardZHY** [comment]
I've just made it working on Legacy Fabric 1.8.9 in IDEA

**Comment by HowardZHY** [comment]
Now I've made it working on Forge 1.8.9. The LF one working on 1.12.2 too. Both tested with Optifine.
![2022-12-04_22 15 47](https://user-images.githubusercontent.com/96782166/205495771-d61cc116-ab63-4455-b0f0-0a43afe5be9b.png)

**Comment by someaddons** [comment]
no
