### ISSUE TITLE
[Bug]: Conflict with sodium mod（minecraft1.19.2 Fabric）

### ISSUE THREAD

**Issue by MCSmallCai** [someaddons/betterfpsdistances#22]
### Describe the bug you're experiencing

When installed with sodium-0.4.4-mc1.19.2 mod, the mod setting strip will be covered and the module will not work

### Reproducability

1

### Mod up to date

- [ ] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://github.com/someaddons/betterfpsdistances

**Comment by venaminecraft** [comment]
Hello @MCSmallCai, the newest release, v2.4 is fixing this issue.
https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance-fabric/files
