### ISSUE TITLE
[Bug]: Incompatible with Meteor client

### ISSUE THREAD

**Issue by AAlchemy** [someaddons/betterfpsdistances#24]
### Describe the bug you're experiencing

Running Farsight with Meteor client causes Meteors storage search module to not render at all. 

### Reproducability

enable Farsight and Meteor, then enable Meteor's storage search module. no tracers or highlight for storage blocks are visible. Removing Farsight will allows Meteor storage search to work again. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/AAlchemy/67557ccfa40a6d54f114c8be662144db

**Comment by someaddons** [comment]
ask meteor client to fix it, I only support fabric/forge
