### ISSUE TITLE
[Bug]: setttings dont save

### ISSUE THREAD

**Issue by harithmf** [someaddons/betterfpsdistances#26]
### Describe the bug you're experiencing

settings dont save

### Reproducability

change settings, they do not save

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/harithmf/82692031d2f5ca068ac2b5492cdf2b22

**Comment by someaddons** [comment]
can't reproduce on the newest
