### ISSUE TITLE
[Bug]: Nether not Rendering

### ISSUE THREAD

**Issue by sherpascott** [someaddons/betterfpsdistances#27]
### Describe the bug you're experiencing

When entering the nether from the overworld on my server nothing renders. Everything is generated already in the area. The error "Ignoring chunk since it's not in the view range" spams my logs. I'm not sure if it was the cause, but removing better fps render distance stopped the issue.

### Reproducability

1. Enter World
2. Enter Nether Portal

(Issue doesn't occur if I quit the game and relaunch and load back into the nether)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/sherpascott/44c3c42005bc8cd41cb443d5d64a93fc

**Comment by someaddons** [comment]
can't reproduce it, your log also does not have it installed
