### ISSUE TITLE
[Bug]: 1.20 Crashes when loading world and sodium is installed

### ISSUE THREAD

**Issue by bdani0717** [someaddons/betterfpsdistances#29]
### Describe the bug you're experiencing

On 1.20 when sodium is installed, the menu loads fine but when I try to load a singleplayer world the game crashes.

### Reproducability

Fabric version 0.14.21
Installed mods:
fabric api 0.83.0 1.20
sodium 0.4.10
betterfpsdist 2.6

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://paste.ee/p/68DKP

**Comment by Mathead253** [comment]
I have the same problem

**Comment by ghost** [comment]
Same here

**Comment by someaddons** [comment]
fixed in 2.7
