### ISSUE TITLE
Lag spikes and performance issues - 1.18.2

### ISSUE THREAD

**Issue by KB-Q** [someaddons/betterfpsdistances#3]
Hi, I'm using this mod (betterfpsdist-fabric-1.18-1.7) along with sodium, lithium, starlight, ferritecore and a bunch of other QoL mods. I'm seeing significantly worse performance when using the mod than without. There are lag spikes every other second or so, which aren't usually there without this mod. 

Now this does say it's for 1.18.1 in the curseforge page, so if this is due to some incompatibility with 1.18.2 let me know. If this is due to something else let me know if it can be fixed. Thank you.

**Comment by someaddons** [comment]
Your lagspikes can't be caused by this mod, as this only edits the distance calculation of which chunks get rendered slightly, which can't possibly caused any additional spikes/load than the normal does. Its probably just correlation not causation that it happened to stop when you tried without.

**Comment by ghost** [comment]
No i have the same problem on 1.19 and Ive tried on 5 different computers. both with and without this mod and i still get lower fps overall for some reason
