### ISSUE TITLE
[Bug]: Mismatched minecraft version with 3.7

### ISSUE THREAD

**Issue by MiyaPixai** [someaddons/betterfpsdistances#31]
### Describe the bug you're experiencing

Installed BetterFPS 3.7 on 1.19.4 and fabric throws a dependency error

`- Mod 'Better FPS distance Mod' (betterfpsdist) 1.19.4-3.7 requires any 1.20.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.4!`

### Reproducability

-Install BetterFPS 3.7 with 1.19.4 - Fabric 0.14.21 loader
-Launch Minecraft

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

x

**Comment by Cape-City** [comment]
![grafik](https://github.com/someaddons/betterfpsdistances/assets/122229367/aad965e5-9946-4ff6-a2c9-711dcb7b7d1c)
Same here, this line in the fabric-mod.json file seems to be wrong:

  "depends": {
    "fabricloader": ">=0.11.3",
    "fabric": "*",
    "minecraft": "1.20.x",   <-----------------------
    "java": ">=17"
  },

**Comment by someaddons** [comment]
fixed, it is the 1.20 version^^
