### ISSUE TITLE
Permission for Modpack request

### ISSUE THREAD

**Issue by Kasax007** [someaddons/betterfpsdistances#32]
### Describe the bug you're experiencing

Hey someaddons, for uploading a modpack on modrinth and to include any mod, I must ask for permission to include them. I would love to include your mod in my pack since it is a great way to improve the performance of the modpack. Therefore I would love to get permission to include your amazing mod in my modpack. If there is any further information you require I am happy to help!
Best regards,
Kasax

### Reproducability

Any modpack on modrinth

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

-

**Comment by someaddons** [comment]
No I dont allow reuploading my files to third party sites
