### ISSUE TITLE
[Bug]: Still rendering in a square?

### ISSUE THREAD

**Issue by t0mtee** [someaddons/betterfpsdistances#33]
### Describe the bug you're experiencing

Either I'm misunderstanding what the mod does or something has gone wrong. The image below shows that the world has still been rendered as a square - unless if I'm just being stupid. Using 1.20 which wasn't an option on this form.
![image](https://github.com/someaddons/betterfpsdistances/assets/33041004/a2ceb21e-ebc2-41b2-8b23-1e76108092c7)

### Reproducability

Load game, fly up, see square.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/OsoaGH/86d696d050532f2edb11f827d44280d1

**Comment by Taleuxss** [comment]
do you have Very Many Players installed

**Comment by Taleuxss** [comment]
nvm the log is right there
try disabling very many players, if that fixes ig mod incompatible

**Comment by t0mtee** [comment]
That has fixed the problem for me, I don't really even know why I have the mod installed. I won't have that many people join my world. Thanks a bunch! You can close this, or keep it open if you want to track / work on incompatibility with VMP.

**Comment by someaddons** [comment]
👍  thanks for finding the issue, ye performance mods are often invasive and cause a lot of incompat.
