### ISSUE TITLE
[Bug]: Make support for Sodium 0.5.1

### ISSUE THREAD

**Issue by mindryder** [someaddons/betterfpsdistances#34]
### Describe the bug you're experiencing

No work with new Sodium 0.5.1

### Reproducability

No work with new Sodium 0.5.1

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

-

**Comment by someaddons** [comment]
every week I gotta update the compat, lol... fixed
