### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wycats0** [someaddons/betterfpsdistances#35]
### Describe the bug you're experiencing

The game crashes when I use Better FPS with other mods.

### Reproducability

Play Minecraft with Forge 47.1.3, Better FPS, Sinytra Connector, Arquitectury, Better Villages, Mo' Villagers, Comes Alive, Biome's O Plenty, Cloth Config, Crash Utilities, Forgified Fabric API, Falling Tree, FPS Reducer, Game Menu Mod Option, Identity, Inventory Profiles, Next, Just Enough Items, Kotlin for Forge, libIPN, Library Ferret, Log Begone, Lost Cities, MineMenu, Not Enough Crashes, Rubidium, TerraBlender and The One Probe; before the game starts, will crashes.
[crash-2023-09-22_20.00.46-client.txt](https://github.com/someaddons/betterfpsdistances/files/12705126/crash-2023-09-22_20.00.46-client.txt)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://mclo.gs/ixYRyGk

**Comment by someaddons** [comment]
you're missing the cupboard mod dependency
