### ISSUE TITLE
[Bug]: crush when clicking on video settings

### ISSUE THREAD

**Issue by eyalgi11** [someaddons/betterfpsdistances#37]
### Describe the bug you're experiencing

when i clicked on the video setting in the options menu it crushed

The game crashed whilst mouseclicked event handler
Error: java.lang.NoSuchMethodError: 'net.minecraft.class_7172$class_7277 net.minecraft.class_7172.method_42399()'

### Reproducability

the mod with fabric api
on fabric version 0.14.22 on minecraft version 1.19.2

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/eyalgi11/e168f73c13cb8b9f22c771465d43e6c3

**Comment by someaddons** [comment]
fixed in 3.7
