### ISSUE TITLE
[Bug]: Crash on Starting with Quilt

### ISSUE THREAD

**Issue by blumenkohlbinary** [someaddons/betterfpsdistances#38]
### Describe the bug you're experiencing

I have created a complete, clean version of Minecraft 1.20.1 that runs with Quilt 0.21.0 and QFAPI-7.4.0. After that, I installed the BetterFPSDistances mod in version 4.0. However, this led to a game crash, accompanied by the following error message:

"-- Error 1 --
Better FPS Distance Mod requires the version [1.20.1-1.5, ∞) of Cupboard, which is missing!"

The strange thing about this is that this problem does not occur in version 3.7 of BetterFPSDistances, but only in the higher versions.

### Reproducability

1. Reinstall Minecraft 1.20.1
2. Install Quilt 0.21.0
3. QFAPI-7.4.0. and Paste BetterFPSDistances 4.0 into mods folder
4. Start
5. Error message

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

https://gist.github.com/Antipartie/5e01e70c9e48d1df267fa717a7427669

**Comment by someaddons** [comment]
you need to add https://www.curseforge.com/minecraft/mc-mods/cupboard
