### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 1936268516** [someaddons/betterfpsdistances#39]
### Describe the bug you're experiencing

Forge-1.20.1-3.9
Forge-47.2.1

### Reproducability

boot crash

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/1936268516/f57d3ce239b8c93e5e695edf36db60e6

**Comment by someaddons** [comment]
the mod isnt even loaded in that log
