### ISSUE TITLE
[Bug]: No Option When Using Optifine

### ISSUE THREAD

**Issue by SaltSouls** [someaddons/betterfpsdistances#4]
### Describe the bug you're experiencing

The option slider for increasing the HRdist doesn't appear in any of the video settings when using optifine, making it impossible to use the two together.

As a side note. It would be nice to have a little bit of a fog/fade effect for the chunks beneath you that are unloading. That way it doesn't look so jarring when you set it to a lower amount, which causes those unloaded chunks to just vanish beneath you, leaving a large hole. I think a fading effect would work fine(may be easier than rendering fog to cover the unloaded chunks), making it so the closer the chunk gets to unloading, the more transparent it gets, until it is eventually just invisible(then it unloads).

### Reproducability

1. Install optifine and betterfpsdistances.
2. Launch game.
3. Go to options/video settings
4. Check all video setting
5 Be sad

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/SaltSouls/f5b215c943cc152ebf20cd5ac2db5621

**Comment by someaddons** [comment]
Not a bug, optifine removes all video options and replace it with their own. You can still modify the setting via config
