### ISSUE TITLE
[Bug]: Game crashed error on launch

### ISSUE THREAD

**Issue by toukent23** [someaddons/betterfpsdistances#40]
### Describe the bug you're experiencing

forge vers: forge-1.20.1-47.2.5-installer
mod vers: betterfpsdist-1.20.1-3.8

I'm trying to run this with other mods, but even when i load it by itself it still crashes. Reinstalled MC and it still crashed.

Error w/o other mods:

- **Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered**
[error log without mods.txt](https://github.com/someaddons/betterfpsdistances/files/13326064/error.log.without.mods.txt)

Error w/ other mods:

- **Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance**
[error log with mods.txt](https://github.com/someaddons/betterfpsdistances/files/13326065/error.log.with.mods.txt)

### Reproducability

fresh install of mc
forge vers: forge-1.20.1-47.2.5-installer
mod vers: betterfpsdist-1.20.1-3.8

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

i dont use github

**Comment by PickyPixelStudio** [comment]
Mod need [Cupboard](https://www.curseforge.com/minecraft/mc-mods/cupboard)
Always check [Dependencies](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance/relations/dependencies)

**Comment by toukent23** [comment]
got it thanks for the help, it works now!
