### ISSUE TITLE
1.20.4 Support?

### ISSUE THREAD

**Issue by Zorklis** [someaddons/betterfpsdistances#42]
### Describe the bug you're experiencing

-

### Reproducability

-

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Fabric

### Logs

-

**Comment by nickcat1** [comment]
Support for 1.20.4 exists. Here's a link! [1.20.x](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance-fabric/files/5136724)

**Comment by someaddons** [comment]
released 1.21, not going to do the small intermediary versions
