### ISSUE TITLE
[Bug]: [1.20.1] Mixin fails to apply to Embeddium (unofficial sodium fork)

### ISSUE THREAD

**Issue by border999** [someaddons/betterfpsdistances#43]
### Describe the bug you're experiencing

Looks like your mod is expecting a different flavor of sodium and doesn't account for if it runs with forks of Sodium. Also your minecraft version list doesn't include a 1.20.
betterfpsdist-1.20.1-4.1
[1.20.1] Embeddium 0.3.0

### Reproducability

Try launching them together.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18

### Modloader version

Forge

### Logs

https://gist.github.com/border999/d48f6cd7c080c7e1d7d9cc917c65b76b

**Comment by captinwill** [comment]
got the same exact issue needs fixed

**Comment by someaddons** [comment]
was simply sodium changing things again, making the newest versions incompatible, released an update
