### ISSUE TITLE
[Bug]: Possible incompatibility with Embeddium, (and maybe Pluto and Canary?) 1.19.2

### ISSUE THREAD

**Issue by DigitalWendigo** [someaddons/betterfpsdistances#44]
### Describe the bug you're experiencing

There seems to be an incompatibility with Better FPS Render Distance, and Embeddium, with another possibility being somehow linked to Pluto and Canary? 
This can not seemingly be reproduced with just Better FPS Render Distance, or with just Embeddium, which is why I believe it's some kind of incompatibility. 
The log file provided below, states it's some kind of OpenAl issue. 
I've already reported the issue on Embeddium's side, and there the author suggested I make a bug report here, since they can not fix it on their end. (Link: https://github.com/embeddedt/embeddium/issues/203 )

If more information or testing is required, let me know. 

### Reproducability

1. Install Embeddium and any possible addons for it. 
1.1. Optionally install Pluto and Canary. (This is optional because I have some instances where this still happened without them, but with both installed, it happened almost every time without fail.)  
2. Load up a world, preferably not a flat one and one with some elevation and forests. 
3. Quickly ascend and decend along the Y axis in succession, sometimes multiple times. 
4. Observe some chunks failing to render and remain 'empty'. 
5. Place a block in these visually glitched out chunks and observe the glitch disappearing. 

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

[<script src="https://gist.github.com/DigitalWendigo/c602f21f76ea5fbbea7248c7b0a05aa1.js"></script>](https://gist.github.com/DigitalWendigo/c602f21f76ea5fbbea7248c7b0a05aa1)

**Comment by someaddons** [comment]
fixed in 4.1, 1.19.2 had some old logic
