### ISSUE TITLE
[Bug]: Not working with latest versions of Embeddium/Xenon on Forge

### ISSUE THREAD

**Issue by BlackTalons** [someaddons/betterfpsdistances#45]
### Describe the bug you're experiencing

Mod ignores any configuration and has no visual effect.

### Reproducability

Installed the mod with Embeddium 0.3.5 on an otherwise clean Forge instance. 
Tried as well with other versions of Embeddium for Forge 1.20.1, and Xenon, a fork of Embeddium.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

-

**Comment by someaddons** [comment]
fixed in 4.3
