### ISSUE TITLE
[Bug]: Incompatability with Gems and Jewels mod

### ISSUE THREAD

**Issue by 1ezekiil** [someaddons/betterfpsdistances#46]
### Describe the bug you're experiencing

Game crashes when i'm trying to run Gems and Jewels with Better FPS.
The loading screen appears for a second then minecraft crashes.
I'm disable all mods in my modpack except these two, so I'm sure.

### Reproducability

Install Better FPS Render Distance and Gems and Jewels then run launcher.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.19

### Modloader version

Forge

### Logs

https://gist.github.com/1ezekiil/998f2fa757c0bdd50b2ce6468d1393c5

**Comment by someaddons** [comment]
you just have your gems and jewels config crashing:
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid TOML data: entry "[kunzite_NetherOreGenEnabled]" defined twice in its table.

nothing to do with betterfps
