### ISSUE TITLE
[Not Really a Bug]: Mark the mod in Curseforge as 1.18.2 Compatible

### ISSUE THREAD

**Issue by Archilyte** [someaddons/betterfpsdistances#5]
### Describe the bug you're experiencing

It's not marked as 1.18.2 compatible on Curseforge despite being compatible, which makes it so that the launcher won't download it onto 1.18.2 forge profiles.

(im making an issue here since u disabled curseforge comments and i have no other way of contacting u)

### Reproducability

Download mod from website, load it into 1.18.2 forge, see results.

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

there are no logs

**Comment by sbgigapsec** [comment]
works on fabric too

**Comment by someaddons** [comment]
done
