### ISSUE TITLE
[Bug]: Crash on startup

### ISSUE THREAD

**Issue by KittyKhrysty** [someaddons/betterfpsdistances#50]
### Describe the bug you're experiencing

Game crashes while loading when betterfps is in the mods folder, even when it's the only mod installed.

### Reproducability

-Install Forge 47.2.30 for Minecraft 1.20.1
-Only have betterfpsdlist-1.20.1-4.3.jar in mods folder

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

https://gist.github.com/KittyKhrysty/7f8ff35a8814579ae327eb234cbc7864

**Comment by PulcioPappi** [comment]
Same exact thing to me.

[crash-2024-04-28_14.08.33-client.txt](https://github.com/someaddons/betterfpsdistances/files/15142146/crash-2024-04-28_14.08.33-client.txt)

**Comment by someaddons** [comment]
you need to install https://www.curseforge.com/minecraft/mc-mods/cupboard aswell, might've not properly marked that on curseforge
