### ISSUE TITLE
[Bug]: Mod does not work at all

### ISSUE THREAD

**Issue by BxRWolfDan** [someaddons/betterfpsdistances#54]
### Describe the bug you're experiencing

I've installed the mod, loaded up a world, changed the setting to the minimum and, checked if caves are being rendered very deep. Low and behold, they were being rendered when, they weren't supposed to be. I've tried the Forge version of this mod and, it worked, don't understand why the Fabric version doesn't. Screenshots of issue below:
![2024-09-03_19 19 09](https://github.com/user-attachments/assets/c76c47e4-3c1a-4625-bb36-917b9ba8d8b1)
![2024-09-03_19 19 21](https://github.com/user-attachments/assets/bedeb28e-5391-4f17-bbba-6814a6dd4b43)

### Reproducability

- Install mod
- Set Minimum Y Render Distance in Settings
- Load any World with Cave Generation

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21

### Modloader version

Fabric

### Logs

https://gist.github.com/BxRWolfDan/08ae32a79fcb93e1d952dc6c2b307111#file-gistfile1-txt

**Comment by someaddons** [comment]
You want to set the stretch value to higher than 100% to hide any sections, setting it lower just makes it show more.
That said the effects might not be that noticeable at high render distance due to a small bug in the distance calc, which is fixed in v6.0
