### ISSUE TITLE
[Bug]: render distance can penetrate blocks

### ISSUE THREAD

**Issue by fzrdwa123456** [someaddons/betterfpsdistances#55]
### Describe the bug you're experiencing

render distance can penetrate blocks

### Reproducability

render distance to 2 chunks, then bring up the options provided by the mod and turn it up
![屏幕截图 2024-10-04 193021](https://github.com/user-attachments/assets/f5ebc434-b405-4b8c-9b2c-718949550ae9)

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.20.1

### Modloader version

Forge

### Logs

No log

**Comment by fzrdwa123456** [comment]
minecraft 1.20.1 forge 47.3.10 better fps 6.0

**Comment by fzrdwa123456** [comment]
Other versions are expected to have this problem as well

**Comment by someaddons** [comment]
well thats just how the mod works, if you scale the distance way down it might hide the stuff below you

**Comment by fzrdwa123456** [comment]
> well thats just how the mod works, if you scale the distance way down it might hide the stuff below you

So this is not a bug but normal, so is there any way to avoid this problem

**Comment by someaddons** [comment]
I mean if you do not want this you just dont put the sliders to the setting?

**Comment by fzrdwa123456** [comment]
> I mean if you do not want this you just dont put the sliders to the setting?

There are no more issues, anyway, thank you for making the mod that made my computer run Minecraft smoothly.
