### ISSUE TITLE
[suggestion] a version for fabric 0.14.25 in Minecraft 1.16.5

### ISSUE THREAD

**Issue by KayziiLOL** [someaddons/betterfpsdistances#56]
Hello, I would like to know if you could make this mod for Minecraft 1.16.5 but compatible with fabric 0.14.25?

It's just that in that version optifabric works and I have better performance in fabric than in forge (using and not using optifine/embeddium)

Thanks.

**Comment by someaddons** [comment]
hi, sorry but that version is too old/not used by enough ppl for me to spend time on
