### ISSUE TITLE
[F-req] Better config

### ISSUE THREAD

**Issue by sbgigapsec** [someaddons/betterfpsdistances#6]
- Problem:
The config needs to accessed through text file with Sodium.
The config is less intuitive.
It cannot increase render distance in Z dir. (I know I can set it lower than 1 but that makes fog buggy looking)
- Feature request:
Add config button to sodium page.
Add functionality to stretch the sphere seperataly in each axis
Make the fog strech in same manner
Also maybe replace the render distance setting with three sliders so as to have precise chunk distance manipulation of each axis.

**Comment by someaddons** [comment]
X/Z distances are determined by the normal render distance slider, I dont think it makes any sense to seperate X/Z from another.
I will not add any extra compat for sodium, if they choose to completely remove the normal options and make mod compat worse that is on them.

**Comment by sbgigapsec** [comment]
Yeah a small mistake on my side. I was using normal math coordinate system for my problem. Just realised that in minecraft Y coordinate is the vertical coordinate and that was what was kindof giving me problems.
