### ISSUE TITLE
[Bug]: Mod Config stays default value

### ISSUE THREAD

**Issue by Vran-n** [someaddons/betterfpsdistances#7]
### Describe the bug you're experiencing

The stretch value in the config file doesn't apply in the game

### Reproducability

1. Install the Mod for 1.16.5
2. Go to the config file
3. Change the value of "stretch" other than the default value

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.16.5

### Modloader version

Forge

### Logs

https://gist.github.com/randwn/235890ba9eddb735c56e8ea9a7bbda09

**Comment by someaddons** [comment]
fixed in 1.2
