### ISSUE TITLE
Support for Rubidium and Distant Horizons for 1.16.5?

### ISSUE THREAD

**Issue by Vran-n** [someaddons/betterfpsdistances#8]
Hello, I was wondering if you are able to provide support for Rubidium since it doesn't work with it, runs with it though. 
It doesn't draw the LOD's from Distant Horizons when the chunks are unloaded by this mod. It works in 1.18.1 but not in this version.

**Comment by someaddons** [comment]
no I dont plan to backport compat, ask rubidium since they break it 🤷
