### ISSUE TITLE
Rubidium

### ISSUE THREAD

**Issue by CuriousGamer2** [someaddons/betterfpsdistances#9]
I don't know where to ask this so I'll just write my question here. Since Betterfps Render Distance is compatible with most mods, does that include optimization mods like Rubidium? [Forge port of Sodium].

**Comment by DigitalWendigo** [comment]
It throws an error in the log file when Rubidium is installed, mentioning something about 'mixin apply failed."
I posted this issue in the Rubidium github issue tracker. 
https://github.com/Asek3/Rubidium/issues/107#issue-1218998457 
Maybe with the help of both mod authors, we will be able to figure out a solid answer.

**Comment by someaddons** [comment]
the 1.18 version actually should work with it, 1.16 doesnt. And I don't think I'd like to get engaged with such a character that Rubidium dev displays, so I'll pass on investing time to make it work
